# Generated by Django 5.1 on 2024-08-27 23:01

from django.db import migrations


from django.db import migrations

def populate_status(apps, schemaeditor):
    entries = {
        "In Progress": "The issue is still in progress",
        "Done": "The issue has been resolved"
    }
    Status = apps.get_model("issues", "Status")
    for key, value in entries.items():
        status_obj = Status(name=key,  description=value)
        status_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_status),
    ]
