# Generated by Django 5.1 on 2024-09-04 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20240827_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='post',
            name='issue',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.status'),
        ),
    ]
